<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <Reference Include="FargowiltasSouls">
	    <HintPath>..\..\ModReader\FargowiltasSouls\FargowiltasSouls.dll</HintPath>
	  </Reference>
	  <Reference Include="Luminance">
	    <HintPath>..\..\ModReader\Luminance\Luminance.dll</HintPath>
	  </Reference>
	  <Reference Include="ssm">
	    <HintPath>..\..\ModReader\ssm\ssm.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<!-- References -->

</Project>